name: 'CI'
on:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build stuff
        run: echo 'hello'
  
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Test stuff
        run: echo 'hello'

  test-matrix:
    name: test-matrix (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        node: [10, 12, 14]
    steps:
      - name: Test stuff
        run: echo 'hello'

    after-matrix:
      runs-on: ubuntu-latest
      needs: [test-matrix]
      steps:
        - name: Test stuff
        run: echo 'hello'