name: 'CI'
on:
  push:
  pull_request:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build stuff
        run: echo 'hello'
  
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Test stuff
        run: echo 'hello'

  test-matrix:
    name: test-matrix (Node ${{ matrix.node }})
    runs-on: ubuntu-latest
    needs: [build]
    strategy:
      matrix:
        node: [10, 12, 14]
    steps:
      - name: Test stuff
        run: echo 'hello'